# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/2.8.12.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/2.8.12.1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/local/Cellar/cmake/2.8.12.1/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/darrentsung/Documents/Personal/Coding/ocean-breeze

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/darrentsung/Documents/Personal/Coding/ocean-breeze

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/2.8.12.1/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/2.8.12.1/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/2.8.12.1/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/2.8.12.1/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/2.8.12.1/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/darrentsung/Documents/Personal/Coding/ocean-breeze/CMakeFiles /Users/darrentsung/Documents/Personal/Coding/ocean-breeze/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/darrentsung/Documents/Personal/Coding/ocean-breeze/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Ocean-breeze

# Build rule for target.
Ocean-breeze: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Ocean-breeze
.PHONY : Ocean-breeze

# fast build rule for target.
Ocean-breeze/fast:
	$(MAKE) -f CMakeFiles/Ocean-breeze.dir/build.make CMakeFiles/Ocean-breeze.dir/build
.PHONY : Ocean-breeze/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f lib/glfw/CMakeFiles/uninstall.dir/build.make lib/glfw/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) -f lib/glfw/src/CMakeFiles/glfw.dir/build.make lib/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named Boing

# Build rule for target.
Boing: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Boing
.PHONY : Boing

# fast build rule for target.
Boing/fast:
	$(MAKE) -f lib/glfw/examples/CMakeFiles/Boing.dir/build.make lib/glfw/examples/CMakeFiles/Boing.dir/build
.PHONY : Boing/fast

#=============================================================================
# Target rules for targets named Gears

# Build rule for target.
Gears: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Gears
.PHONY : Gears

# fast build rule for target.
Gears/fast:
	$(MAKE) -f lib/glfw/examples/CMakeFiles/Gears.dir/build.make lib/glfw/examples/CMakeFiles/Gears.dir/build
.PHONY : Gears/fast

#=============================================================================
# Target rules for targets named Simple

# Build rule for target.
Simple: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Simple
.PHONY : Simple

# fast build rule for target.
Simple/fast:
	$(MAKE) -f lib/glfw/examples/CMakeFiles/Simple.dir/build.make lib/glfw/examples/CMakeFiles/Simple.dir/build
.PHONY : Simple/fast

#=============================================================================
# Target rules for targets named Split View

# Build rule for target.
Split\ View: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 "Split View"
.PHONY : Split\ View

# fast build rule for target.
Split\ View/fast:
	$(MAKE) -f "lib/glfw/examples/CMakeFiles/Split View.dir/build.make" "lib/glfw/examples/CMakeFiles/Split View.dir/build"
.PHONY : Split\ View/fast

#=============================================================================
# Target rules for targets named Wave

# Build rule for target.
Wave: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Wave
.PHONY : Wave

# fast build rule for target.
Wave/fast:
	$(MAKE) -f lib/glfw/examples/CMakeFiles/Wave.dir/build.make lib/glfw/examples/CMakeFiles/Wave.dir/build
.PHONY : Wave/fast

#=============================================================================
# Target rules for targets named accuracy

# Build rule for target.
accuracy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 accuracy
.PHONY : accuracy

# fast build rule for target.
accuracy/fast:
	$(MAKE) -f lib/glfw/tests/CMakeFiles/accuracy.dir/build.make lib/glfw/tests/CMakeFiles/accuracy.dir/build
.PHONY : accuracy/fast

#=============================================================================
# Target rules for targets named clipboard

# Build rule for target.
clipboard: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clipboard
.PHONY : clipboard

# fast build rule for target.
clipboard/fast:
	$(MAKE) -f lib/glfw/tests/CMakeFiles/clipboard.dir/build.make lib/glfw/tests/CMakeFiles/clipboard.dir/build
.PHONY : clipboard/fast

#=============================================================================
# Target rules for targets named defaults

# Build rule for target.
defaults: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 defaults
.PHONY : defaults

# fast build rule for target.
defaults/fast:
	$(MAKE) -f lib/glfw/tests/CMakeFiles/defaults.dir/build.make lib/glfw/tests/CMakeFiles/defaults.dir/build
.PHONY : defaults/fast

#=============================================================================
# Target rules for targets named events

# Build rule for target.
events: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 events
.PHONY : events

# fast build rule for target.
events/fast:
	$(MAKE) -f lib/glfw/tests/CMakeFiles/events.dir/build.make lib/glfw/tests/CMakeFiles/events.dir/build
.PHONY : events/fast

#=============================================================================
# Target rules for targets named fsaa

# Build rule for target.
fsaa: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fsaa
.PHONY : fsaa

# fast build rule for target.
fsaa/fast:
	$(MAKE) -f lib/glfw/tests/CMakeFiles/fsaa.dir/build.make lib/glfw/tests/CMakeFiles/fsaa.dir/build
.PHONY : fsaa/fast

#=============================================================================
# Target rules for targets named gamma

# Build rule for target.
gamma: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gamma
.PHONY : gamma

# fast build rule for target.
gamma/fast:
	$(MAKE) -f lib/glfw/tests/CMakeFiles/gamma.dir/build.make lib/glfw/tests/CMakeFiles/gamma.dir/build
.PHONY : gamma/fast

#=============================================================================
# Target rules for targets named glfwinfo

# Build rule for target.
glfwinfo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glfwinfo
.PHONY : glfwinfo

# fast build rule for target.
glfwinfo/fast:
	$(MAKE) -f lib/glfw/tests/CMakeFiles/glfwinfo.dir/build.make lib/glfw/tests/CMakeFiles/glfwinfo.dir/build
.PHONY : glfwinfo/fast

#=============================================================================
# Target rules for targets named iconify

# Build rule for target.
iconify: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 iconify
.PHONY : iconify

# fast build rule for target.
iconify/fast:
	$(MAKE) -f lib/glfw/tests/CMakeFiles/iconify.dir/build.make lib/glfw/tests/CMakeFiles/iconify.dir/build
.PHONY : iconify/fast

#=============================================================================
# Target rules for targets named joysticks

# Build rule for target.
joysticks: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 joysticks
.PHONY : joysticks

# fast build rule for target.
joysticks/fast:
	$(MAKE) -f lib/glfw/tests/CMakeFiles/joysticks.dir/build.make lib/glfw/tests/CMakeFiles/joysticks.dir/build
.PHONY : joysticks/fast

#=============================================================================
# Target rules for targets named modes

# Build rule for target.
modes: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 modes
.PHONY : modes

# fast build rule for target.
modes/fast:
	$(MAKE) -f lib/glfw/tests/CMakeFiles/modes.dir/build.make lib/glfw/tests/CMakeFiles/modes.dir/build
.PHONY : modes/fast

#=============================================================================
# Target rules for targets named peter

# Build rule for target.
peter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 peter
.PHONY : peter

# fast build rule for target.
peter/fast:
	$(MAKE) -f lib/glfw/tests/CMakeFiles/peter.dir/build.make lib/glfw/tests/CMakeFiles/peter.dir/build
.PHONY : peter/fast

#=============================================================================
# Target rules for targets named reopen

# Build rule for target.
reopen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 reopen
.PHONY : reopen

# fast build rule for target.
reopen/fast:
	$(MAKE) -f lib/glfw/tests/CMakeFiles/reopen.dir/build.make lib/glfw/tests/CMakeFiles/reopen.dir/build
.PHONY : reopen/fast

#=============================================================================
# Target rules for targets named sharing

# Build rule for target.
sharing: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sharing
.PHONY : sharing

# fast build rule for target.
sharing/fast:
	$(MAKE) -f lib/glfw/tests/CMakeFiles/sharing.dir/build.make lib/glfw/tests/CMakeFiles/sharing.dir/build
.PHONY : sharing/fast

#=============================================================================
# Target rules for targets named tearing

# Build rule for target.
tearing: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tearing
.PHONY : tearing

# fast build rule for target.
tearing/fast:
	$(MAKE) -f lib/glfw/tests/CMakeFiles/tearing.dir/build.make lib/glfw/tests/CMakeFiles/tearing.dir/build
.PHONY : tearing/fast

#=============================================================================
# Target rules for targets named threads

# Build rule for target.
threads: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 threads
.PHONY : threads

# fast build rule for target.
threads/fast:
	$(MAKE) -f lib/glfw/tests/CMakeFiles/threads.dir/build.make lib/glfw/tests/CMakeFiles/threads.dir/build
.PHONY : threads/fast

#=============================================================================
# Target rules for targets named title

# Build rule for target.
title: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 title
.PHONY : title

# fast build rule for target.
title/fast:
	$(MAKE) -f lib/glfw/tests/CMakeFiles/title.dir/build.make lib/glfw/tests/CMakeFiles/title.dir/build
.PHONY : title/fast

#=============================================================================
# Target rules for targets named windows

# Build rule for target.
windows: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 windows
.PHONY : windows

# fast build rule for target.
windows/fast:
	$(MAKE) -f lib/glfw/tests/CMakeFiles/windows.dir/build.make lib/glfw/tests/CMakeFiles/windows.dir/build
.PHONY : windows/fast

src/app.o: src/app.cpp.o
.PHONY : src/app.o

# target to build an object file
src/app.cpp.o:
	$(MAKE) -f CMakeFiles/Ocean-breeze.dir/build.make CMakeFiles/Ocean-breeze.dir/src/app.cpp.o
.PHONY : src/app.cpp.o

src/app.i: src/app.cpp.i
.PHONY : src/app.i

# target to preprocess a source file
src/app.cpp.i:
	$(MAKE) -f CMakeFiles/Ocean-breeze.dir/build.make CMakeFiles/Ocean-breeze.dir/src/app.cpp.i
.PHONY : src/app.cpp.i

src/app.s: src/app.cpp.s
.PHONY : src/app.s

# target to generate assembly for a file
src/app.cpp.s:
	$(MAKE) -f CMakeFiles/Ocean-breeze.dir/build.make CMakeFiles/Ocean-breeze.dir/src/app.cpp.s
.PHONY : src/app.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/Ocean-breeze.dir/build.make CMakeFiles/Ocean-breeze.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/Ocean-breeze.dir/build.make CMakeFiles/Ocean-breeze.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/Ocean-breeze.dir/build.make CMakeFiles/Ocean-breeze.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/pnoise.o: src/pnoise.cpp.o
.PHONY : src/pnoise.o

# target to build an object file
src/pnoise.cpp.o:
	$(MAKE) -f CMakeFiles/Ocean-breeze.dir/build.make CMakeFiles/Ocean-breeze.dir/src/pnoise.cpp.o
.PHONY : src/pnoise.cpp.o

src/pnoise.i: src/pnoise.cpp.i
.PHONY : src/pnoise.i

# target to preprocess a source file
src/pnoise.cpp.i:
	$(MAKE) -f CMakeFiles/Ocean-breeze.dir/build.make CMakeFiles/Ocean-breeze.dir/src/pnoise.cpp.i
.PHONY : src/pnoise.cpp.i

src/pnoise.s: src/pnoise.cpp.s
.PHONY : src/pnoise.s

# target to generate assembly for a file
src/pnoise.cpp.s:
	$(MAKE) -f CMakeFiles/Ocean-breeze.dir/build.make CMakeFiles/Ocean-breeze.dir/src/pnoise.cpp.s
.PHONY : src/pnoise.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Ocean-breeze"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... uninstall"
	@echo "... glfw"
	@echo "... Boing"
	@echo "... Gears"
	@echo "... Simple"
	@echo "... Split View"
	@echo "... Wave"
	@echo "... accuracy"
	@echo "... clipboard"
	@echo "... defaults"
	@echo "... events"
	@echo "... fsaa"
	@echo "... gamma"
	@echo "... glfwinfo"
	@echo "... iconify"
	@echo "... joysticks"
	@echo "... modes"
	@echo "... peter"
	@echo "... reopen"
	@echo "... sharing"
	@echo "... tearing"
	@echo "... threads"
	@echo "... title"
	@echo "... windows"
	@echo "... src/app.o"
	@echo "... src/app.i"
	@echo "... src/app.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/pnoise.o"
	@echo "... src/pnoise.i"
	@echo "... src/pnoise.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

